version: 7.4.4.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore .\Source\
build:
  project: Source\Sagitta.sln
  publish_nuget: true
  verbosity: minimal
cache:
- Source\packages -> **\packages.config
configuration: Release
deploy:
- provider: NuGet
  api_key:
    secure: NDm0vtN/grWnX8Zn7p7cxU7nHTu9w3VYqa+MBQm0SXZqkga2/JS3ngbtxxUoH+b0
  artifact: /.*\.nupkg/
  on:
    branch: /master/
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
notifications:
- provider: Slack
  incoming_webhook:
    secure: IY0URIfO7RU35GI0Hz1uzZo6GjX5cZP1glxYAGwwpunZBW5LqfbfkpsafcuTcaC1fmPD+xXck4UmWp4RS4cUro2+Cpyi55Q2TKSp9kENiV+BLeD767QVWMO3Zz7PiqdYKpE1dmiYPTe8SAcYg0asM873SKkcJ8rhUan/mgpsluOAFF9qTxX6LKbJAd6p4Rb/
  channel: ci
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
nuget:
  disable_publish_on_pr: true
pull_requests:
  do_not_increment_build_number: true
skip_tags: true